### ISSUE TITLE
Data can't be uploaded

### ISSUE THREAD

**Issue by mmaelicke** [data-hydenv/data#12]
Dear @SebGrue please check your hourly quality checked data file. 

My upload script is failing, most likely due to unkown and/or missing header names in the file: https://github.com/data-hydenv/data/blob/master/hobo/2022/hourly/10347328_Th.csv

Please check the file and drop a comment in case you can't find the issue. Thanks!

**Comment by mmaelicke** [comment]
Thank you for the correction!

**Comment by SebGrue** [comment]
@mmaelicke Adjusted the header, hope it works now. If not, please leave me a message. Thanks!
