### ISSUE TITLE
Questionable HOBO locations

### ISSUE THREAD

**Issue by mmaelicke** [data-hydenv/data#4]
@data-hydenv/students ,
There are two questionable HOBO locations in the Metadata file. Please check them. The cells are marked red in the doc. If the location is correct, just remove the red markup.

### HOBO ID 10350028

![image](https://user-images.githubusercontent.com/2826034/102970928-b25dc500-44f8-11eb-8e6d-9edc16d7d6b3.png)

### HOBO ID 10347371

![image](https://user-images.githubusercontent.com/2826034/102971096-ff419b80-44f8-11eb-852f-1b29a0c0e940.png)

**Comment by Acefall** [comment]
Fixed Location of HOBO ID 10380028.

**Comment by mmaelicke** [comment]
> Fixed Location of HOBO ID 10380028.

Thank you!

**Comment by mmaelicke** [comment]
Thanks for fixing, will close the issue again.
